# Site settings
title: Pranav Mital
email: 
url: https://example.github.io
description: Hi, my name is Pranav. Welcome to my official website!

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Pranav Mital

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/pranavmital
  - title: twitter
    url: https://twitter.com/prxnav
  - title: linkedin
    url: https://www.linkedin.com/in/pranavmital/

#  - title: envelope
#    url: mailto:pranavmital27@gmail.com


# Build settings
markdown: kramdown
permalink: pretty
